/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CommunityForumService } from "../communityForum.service";
import { CommunityForumCreateInput } from "./CommunityForumCreateInput";
import { CommunityForum } from "./CommunityForum";
import { CommunityForumFindManyArgs } from "./CommunityForumFindManyArgs";
import { CommunityForumWhereUniqueInput } from "./CommunityForumWhereUniqueInput";
import { CommunityForumUpdateInput } from "./CommunityForumUpdateInput";

export class CommunityForumControllerBase {
  constructor(protected readonly service: CommunityForumService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CommunityForum })
  async createCommunityForum(
    @common.Body() data: CommunityForumCreateInput
  ): Promise<CommunityForum> {
    return await this.service.createCommunityForum({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        createdDate: true,
        description: true,
        id: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [CommunityForum] })
  @ApiNestedQuery(CommunityForumFindManyArgs)
  async communityForums(
    @common.Req() request: Request
  ): Promise<CommunityForum[]> {
    const args = plainToClass(CommunityForumFindManyArgs, request.query);
    return this.service.communityForums({
      ...args,
      select: {
        createdAt: true,
        createdDate: true,
        description: true,
        id: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CommunityForum })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async communityForum(
    @common.Param() params: CommunityForumWhereUniqueInput
  ): Promise<CommunityForum | null> {
    const result = await this.service.communityForum({
      where: params,
      select: {
        createdAt: true,
        createdDate: true,
        description: true,
        id: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CommunityForum })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCommunityForum(
    @common.Param() params: CommunityForumWhereUniqueInput,
    @common.Body() data: CommunityForumUpdateInput
  ): Promise<CommunityForum | null> {
    try {
      return await this.service.updateCommunityForum({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          createdDate: true,
          description: true,
          id: true,
          title: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CommunityForum })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCommunityForum(
    @common.Param() params: CommunityForumWhereUniqueInput
  ): Promise<CommunityForum | null> {
    try {
      return await this.service.deleteCommunityForum({
        where: params,
        select: {
          createdAt: true,
          createdDate: true,
          description: true,
          id: true,
          title: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
