/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CommunityForumCreateNestedManyWithoutUsersInput } from "./CommunityForumCreateNestedManyWithoutUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsDate,
} from "class-validator";
import { Type } from "class-transformer";
import { EventCreateNestedManyWithoutUsersInput } from "./EventCreateNestedManyWithoutUsersInput";
import { LocationCreateNestedManyWithoutUsersInput } from "./LocationCreateNestedManyWithoutUsersInput";
import { MilestoneCreateNestedManyWithoutUsersInput } from "./MilestoneCreateNestedManyWithoutUsersInput";
import { ParentingTipCreateNestedManyWithoutUsersInput } from "./ParentingTipCreateNestedManyWithoutUsersInput";
import { ProductReviewCreateNestedManyWithoutUsersInput } from "./ProductReviewCreateNestedManyWithoutUsersInput";
import { ResourceCreateNestedManyWithoutUsersInput } from "./ResourceCreateNestedManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { UserProfileCreateNestedManyWithoutUsersInput } from "./UserProfileCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => CommunityForumCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CommunityForumCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CommunityForumCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  communityForums?: CommunityForumCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => EventCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => EventCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => EventCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  events?: EventCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  joinedDate?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => LocationCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => LocationCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => LocationCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  locations?: LocationCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => MilestoneCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => MilestoneCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => MilestoneCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  milestones?: MilestoneCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => ParentingTipCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ParentingTipCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ParentingTipCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  parentingTips?: ParentingTipCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    type: () => ProductReviewCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ProductReviewCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ProductReviewCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  productReviews?: ProductReviewCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => ResourceCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ResourceCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ResourceCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  resources?: ResourceCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: false,
    type: () => UserProfileCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserProfileCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserProfileCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  userProfiles?: UserProfileCreateNestedManyWithoutUsersInput;
}

export { UserCreateInput as UserCreateInput };
